apiVersion: apps/v1
kind: Deployment
metadata:
  name: netconf-sim-deployment
  labels:
    app: netconf-sim
spec:
  selector:
    matchLabels:
      app: netconf-sim
  replicas: 1
  template:
    metadata:
      labels:
        app: netconf-sim
    spec:
      containers:
      - name: netconf-sim
        image: mcguinnessa/netconf-sim:latest
        env:
        - name: PORT 
          value: "1830"
        - name: RSA_PRIVATE_KEY 
          value: "/app/nc-sim.priv"
        - name: USER 
          value: "alex"
        - name: LOGLEVEL 
          value: "debug"
# Use the localhost:32000 path to use image from registry service
# e.g.  image: localhost:32000/hello-app:v3
        ports:
        - containerPort: 1830
#        volumeMounts:
#        - name: "netconf-dir"
#          mountPath: "/shared"
#        command: [ "sh", "-c"]
#        args: ["while true; do echo 'yo' && sleep 5; done;"]
#      volumes:
#      - name: "netconf-dir"
#        persistentVolumeClaim:
#          claimName: "netconf-pvc"


